### ISSUE TITLE
project distributed as module instead of package

### ISSUE THREAD

**Issue by Timtam** [synthizer/synthizer-python#13]
Probably related to #11, but since it might cause some complication i think a new issue serves better.
I noticed that synthizer right now is distributed as module-only, it basically just installs the .so / .pyd file and nothing else, no .pyx, no .pyi and also not the typing indication. I don't know if it is intentional that way although they are to be collected by the setup.py file, but such files can only be included within package projects, not module projects. The solution to this would be to release it as package (probably called synthizer again), containing the .so / .pyd and the typing files etc. To prevent this change from breaking anything, we'd need to add a __init__.py file which either imports all relevant objects by name (preferred), which needs to be maintained whenever something new is added in that should be available at package level, or import *, which will forward everything from the shared lib at package level, but import * should generally be avoided due to namespace pollution etc.

Overall this should be easy to do and i'd be willing to do it, I just need to get a setup that properly builds a wheel to test things (will probably do so under Linux). Its probably best to discuss this before getting started in case i'm missing something important here. And it might introduce some maintenance overhead in the future since new objects need to be re-imported at package level.

**Comment by Timtam** [comment]
I submitted a draft PR which fixes this error without breaking existing code. It now ships the typing support for sure (tested against my pyAGE project) and is extensible in case some other modules have to be added in the future. No further maintenance should be needed due to a 1:1 forward via * import.

**Comment by ahicks92** [comment]
I don't understand the problem.  What I do already should work, and it did work for @chrisnorman7 for a long time.  What actually breaks?  I've never heard of any project having to reexport a C extension to get typing working.

**Comment by Timtam** [comment]
It cannot work by definition, because the wheels don't contain any typing declarations right now (just download one of the wheels and check for yourself). All they contain until this PR is the pyd/so file and thats it. One module and nothing else, except the egg metadata. Thats what this PR changes, it packages everything as a package instead of a module and therefore can supply the typing definitions with it. Chris probably is using an old version that worked previously? I don't know, but 0.12 deffinitely doesn't contain any typing-relevant files within the wheels.

**Comment by ahicks92** [comment]
I'm not opposed to this change, I just want to make sure I understand.  Looks like the info is in PEP 561, but as usual Python packaging docs are lacking to say the least.

@chrisnorman7 
You wrote the original support for this.

**Comment by chrisnorman7** [comment]
@ahicks92 I did? Well, I did warn you about my memory.

**Comment by ahicks92** [comment]
Yeah, this was back in your typed Python phase iirc. Maybe I'm mixing you up with someone else but I don't think so.

**Comment by ahicks92** [comment]
I've landed the pr. I'm going to wait a week in case @Timtam finds something else to report. (fwiw the Python 3.7 etc. wheels went up the other day)

**Comment by ahicks92** [comment]
this should now be released.
