### ISSUE TITLE
Silently Crashing in Python (Possibly Related to Decreasing Reference Counts)

### ISSUE THREAD

**Issue by StormyNight2020** [synthizer/synthizer-python#3]
After updating to the latest version of Synthizer, I started experiencing unpredictable Python crashing. I can't say for certain, but I think the problem comes from decreasing reference counts since that's the only change I made to my sound system after updating. Crashing happens often but randomly. [Here](https://pastebin.com/FcTzhv3N) is a script containing the bare-bones of my sound player. You'll need an extremely short sound called beep.wav. The script plays it over and over again at random positions 100 times because that's how I can get this to trigger. It's hard to catch the crashing, but it happens quickly whenever it does happen. Any feedback is appreciated.

**Comment by ahicks92** [comment]
Sorry for the delay.  This is now fixed, as far as I can tell.  There was an  obscure race condition when deleting sources.  A release is up with that change.  If you could upgrade and check it I'd appreciate that.

**Comment by StormyNight2020** [comment]
I haven't been able to recreate the issue since updating to the latest version. I'll continue to check, but I definitely think it's fixed. Thank you for looking into it! The time spent is very much appreciated!

**Comment by ahicks92** [comment]
Of course.  And thanks for putting in the time to report.
