### ISSUE TITLE
Runtime Error when attempting to assign to object properties

### ISSUE THREAD

**Issue by StormyNight2020** [synthizer/synthizer-python#8]
I just updated to the latest version (0.12.1) and started running into this problem.

RuntimeError: You cannot directly reassign property objects.                                                            

I get this for basically trying to set anything. (strategies on a context, buffers on generators, ETC) I tried the media player example in the manual and run into the same issue. Am I missing something?

**Comment by ahicks92** [comment]
Yes, that changed. Add .value to your property reads/sets.  If that doesn't fix it I'll investigate further.

**Comment by StormyNight2020** [comment]
That did the trick. Thank you for letting me know. Where's the best place to keep up to date to avoid my confusion in the future?

**Comment by ahicks92** [comment]
As with many projects, I maintain a CHANGES.md in the root of this repository.
